---

- name: Expect the presence of config.xml 
  register: domain_exist
  stat: 
      path: "{{ domain_config_xml }}"

- block:
    - name: Check {{ name_prefix }}.zip
      stat:
        path: "{{ domain_account.home }}/*.zip"
      register: check_domain_zip
    - name: delete zip files
      shell: rm -f *.zip
      args:
        executable: /bin/bash
        chdir: "{{ domain_account.home }}"  
      when: check_domain_zip.stat.exists
    - name: zip {{ domain_account.home }} 
      shell: "cd {{ domain_account.home }}/ && zip -r {{ weblogic_domain_name }}.zip applications/ autodeploy/ bin/ common/ config/ console-ext/ init-info/ lib/ nodemanager/ pending/ security/ servers/"
    - name: copy to ansible server
      fetch:
        src: "{{ domain_account.home }}/{{ weblogic_domain_name }}.zip"
        dest: "{{ weblogic_domain_name }}.zip"  
        flat: true
  when: domain_exist.stat.exists
        
- block:
    - name: copy to second module
      copy:
        src: "{{ weblogic_domain_name }}.zip"
        dest: "{{ domain_account.home }}/{{ weblogic_domain_name }}.zip"                  
    - name: unzip {{ weblogic_domain_name }}.zip
      shell: "cd {{ domain_account.home }}/ &&  unzip {{ name_prefix }}.zip"
  when: not domain_exist.stat.exists