---

- name:   chmod and chown of domains folder
  file:
    path:  "{{ weblogic_install.domains}}"
    owner: "{{weblogic_account.username}}"
    group: "{{weblogic_account.group}}"
    mode:  0775

- name: Create UNIX group ({{ domain_account.group }})
  register: linuxgroup
  group:
      name: "{{ domain_account.group }}"
      gid: "{{ domain_account.gid }}"
      state: present                
                      
- name: Create UNIX user ({{ domain_account.username }})
  when: linuxgroup is success
  user:
    name: "{{ domain_account.username }}"
    home: "{{ domain_account.home }}"
    uid: "{{ domain_account.uid }}"
    group: "{{ domain_account.group }}"
    shell: "{{ domain_account.shell }}"
    password: "{{ weblogic_admin_password | password_hash('sha512') }}"

- name: Add "ll" alias in bashrc
  lineinfile: 
      dest: "{{ domain_account.home }}/.bashrc" 
      line: alias ll="ls -laF"

- name: Fix home directory permission ({{ domain_account.home }})
  file:
      dest: "{{ domain_account.home }}"
      state: directory
      mode: 0770
      
- name: Add {{ user_mem_args_key }} to use urandom in bashrc
  lineinfile: 
      state: present
      path: "{{ domain_account.home }}/.bashrc" 
      regexp: 'export {{ user_mem_args_key }}='
      line: 'export {{ user_mem_args_key }}="-Djava.security.egd=file:/dev/./urandom -XX:MaxPermSize=512M -Dweblogic.security.SSL.ignoreHostnameVerification=true"' # won't pass variable here
            
- name: Add JAVA_HOME environment variariables in bashrc
  lineinfile: 
      state: present
      dest: "{{ domain_account.home }}/.bashrc"
      regexp: 'export JAVA_HOME='
      line: 'export JAVA_HOME="{{ jdk_install.symlink }}"'

- name: Add java/bin folder to path in bashrc
  lineinfile: 
      state: present
      dest: "{{ domain_account.home }}/.bashrc"
      regexp: 'export PATH='
      line: 'export PATH=$JAVA_HOME/bin:$PATH'
            
#- name: Add PS1 in bashrc
#  lineinfile: 
#      dest: "{{ domain_account.home }}/.bashrc" 
#      line: PS1='\[\e[1;32m\][\u@\h \w]\n\$\[\e[0m\]'

- name: Add umask 0022
  lineinfile: 
      dest: "{{ domain_account.home }}/.bashrc" 
      line: umask 0022                  
                
            
- name:     Allow {{domain_account.username}} to sudoers
  lineinfile:
    dest:         /etc/sudoers
    state:        present
    regexp:       '^{{domain_account.username}}'
    line:         '{{domain_account.username}} ALL=(ALL) NOPASSWD: ALL'
    validate:     'visudo -cf %s'                    
      