--- 

- name:     Download config file for security_update
  get_url:
    url:    "{{ security_general.config_url }}"
    dest:   "{{ security_general.config }}"
    owner:  "{{ domain_account.username }}"
    group:  "{{ domain_account.group }}"    
    mode:   0750

- name:     Download secret file for security_update
  get_url:
    url:    "{{ security_general.secret_url }}"
    dest:   "{{ security_general.secret }}"
    owner:  "{{ domain_account.username }}"
    group:  "{{ domain_account.group }}"    
    mode:   0750
    
- name: Expect 172.17.0.2 to be listening on {{ unique_id + 10000|int }}
  wait_for:
      host: "172.17.0.2"
      port: "{{ unique_id + 10000|int }}"
      state: started
      timeout: "{{ timeout.admin }}"      
  register: admin_listen
  
- block:    
    - name: Update add_machine.py template
      template:
        src: add_machine.py.j2
        dest: "{{ staging_folder.domain }}/add_machine.py"
        owner: "{{domain_account.username}}"
        group: "{{domain_account.group}}"
        mode: 0774
              
    - name: Add {{ weblogic_domain_name }}HostAdmin machine and update security/general user online
      shell: "{{ weblogic_install.oracle_home }}/oracle_common/common/bin/wlst.sh {{ staging_folder.domain }}/add_machine.py"
  when: admin_listen.state == 'started'
  
- fail: 
    msg: "The 172.17.0.2 is not listening on {{ unique_id + 10000|int }}"
  when: admin_listen.state != 'started'  
 