---

- name: Expect the correct value of JAVA_HOME in setDomainEnv.sh
  replace:
      path: "{{ setDomainEnv_sh }}"
      regexp: '(.*)JAVA_HOME="[a-zA-Z0-9/_\.]+"'
      replace: '\1JAVA_HOME="{{ jdk_install.symlink }}"'   
