---

- name: Create staging directory
  file: 
    state: directory 
    path: "{{ staging_folder.domain }}"
        
- name: Check "{{ weblogic_node_manager_properties }}"
  stat:
    path: "{{ weblogic_node_manager_properties }}"
  register: nodemanager   

- block:     
    - name: Expect the correct value of ListenAddress in nodemanager.properties
      lineinfile:
          state: present
          path: "{{ weblogic_node_manager_properties }}"
          regexp: 'ListenAddress='
          line: 'ListenAddress=172.17.0.2'
           
    - name: Expect the correct value of ListenPort in nodemanager.properties
      lineinfile:
          state: present
          path: "{{ weblogic_node_manager_properties }}"
          regexp: 'ListenPort='
          line: 'ListenPort={{ unique_id + 20000|int }}'
    
    - name: Expect the correct value of JavaHome in nodemanager.properties
      lineinfile:
          path: "{{ weblogic_node_manager_properties }}"
          regexp: 'JavaHome='
          line: 'JavaHome={{ jdk_install.symlink }}'
  when: nodemanager.stat.exists == true          
  