--- 
    
- name: Expect {{ weblogic_servers[server].instance_address }} to be listening on {{ weblogic_servers[server].instance_port }}
  wait_for:
      host: "{{ weblogic_servers[server].instance_address }}"
      port: "{{ weblogic_servers[server].instance_port }}"
      state: started
      timeout: "{{ timeout.admin }}"      
  register: admin_listen
  
- block:    
    - name: Update nmenroll.py template
      template:
        src: nmenroll.py.j2
        dest: "{{ staging_folder.domain }}/nmenroll.py"
        owner: "{{domain_account.username}}"
        group: "{{domain_account.group}}"
        mode: 0774
              
    - name: Executing nmenroll
      shell: "{{ weblogic_install.oracle_home }}/oracle_common/common/bin/wlst.sh {{ staging_folder.domain }}/nmenroll.py"
  when: admin_listen.state == 'started'
  
- fail: 
    msg: "Fail nmenroll: The {{ weblogic_servers[server].instance_address }} is not listening on {{ weblogic_servers[server].instance_port }}"
  when: admin_listen.state != 'started'  
 